name: sum-example-ci (kotlin)

on:
  pull_request:
    branches: [ main, develop ]

permissions:
    contents: read
    packages: write
    pull-requests: write
    issues: write

jobs:
  build-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Up nodejs v20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci      
      - run: npm test -- --coverage      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}